config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :movies

  resources :lists

  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: %i[list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmarks, only: [:show, :edit, :update, :destroy]
  def index
    @bookmarks = Bookmark.all
  end

  def show
  end

  def new
    @bookmark = Bookmark.new
    @movies = Movie.all
    @lists = List.all
  end

  def create
    @bookmark = Bookmark.new(comment: params["bookmark"]["comment"], movie_id: params["bookmark"]["movie_id"], list_id: params["bookmark"]["list_id"])
    @bookmark.save
    redirect_to bookmarks_path
  end

  def edit
  end

  def update
    @bookmark.update(bookmark_params)
    redirect_to bookmark_path(@bookmark)
  end

  def destroy
    @bookmark.destroy
    # No need for app/views/bookmarks/destroy.html.erb
    redirect_to bookmarks_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end

  def set_bookmarks
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_lists, only: [:show, :edit, :update, :destroy]
  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    # No need for app/views/lists/destroy.html.erb
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:article).permit(:name, :photo)
  end

  def set_lists
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movies, only: [:show, :edit, :update, :destroy]
  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to movies_path
  end

  def edit
  end

  def update
    @movie.update(movie_params)
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie.destroy
    # No need for app/views/movies/destroy.html.erb
    redirect_to movies_path, status: :see_other
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end

  def set_movies
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/index.html.erb
<h1>My Bookmarks</h1>
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li><%= link_to bookmark.comment, bookmark_path(bookmark) %></li>
  <% end %>
</ul>
<hr>
<h3><%= link_to "Add a new bookmark", new_bookmark_path %></h3>

app/views/bookmarks/new.html.erb
<%= simple_form_for(@bookmark) do |f| %>
  <%= f.input :comment %>
  <%= f.input :list_id, collection: @lists.index%>
  <%= f.input :movie_id, collection:  @movies.index%>
  <%= f.button :submit %>
<% end %>

app/views/bookmarks/show.html.erb
<div style="display: flex; justify-content: space-between;">
<ul>
  <li><h1>Bookmark Comment: <%= @bookmark.comment %></h1></li>
  <li><h2>Movie: <%= @bookmark.movie.title %></h2></li>
  <li><h2>List: <%= @bookmark.list.name %></h2></li>
</ul>
  <div style="border: 1px solid black; background-color: lightgray; padding: 10px;">
    <%= link_to "Edit this bookmark", edit_bookmark_path(@bookmark) %>
  </div>
</div>

<hr>
<%= link_to "Back to bookmark", bookmarks_path %>
<%= link_to "Delete this bookmark", bookmark_path(@bookmark.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/lists/edit.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>My Lists</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= cl_image_tag("v1653042811/opq3aikpkny4szldqmux", width: 150, height: 150, crop: :thumb) %></li>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>
<hr>
<h3><%= link_to "Add a new list", new_list_path %></h3>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div style="display: flex; justify-content: space-between;">
  <h1><%= @list.name %></h1>
  <%= cl_image_tag("v1653042811/opq3aikpkny4szldqmux", width: 400, height: 300, crop: :fill) %>
  <div style="border: 1px solid black; background-color: lightgray; padding: 10px;">
    <%= link_to "Edit this list", edit_list_path(@list) %>
  </div>
</div>

<hr>
<%= link_to "Back to list", lists_path %>
<%= link_to "Delete this list", list_path(@list.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

app/views/movies/edit.html.erb
<%= simple_form_for(@movie) do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :poster_url %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<h1>My Movies</h1>
<ul>
  <% @movies.each do |movie| %>
    <li><%= link_to movie.title, movie_path(movie) %></li>
  <% end %>
</ul>
<hr>
<h3><%= link_to "Add a new movie", new_movie_path %></h3>

app/views/movies/new.html.erb
<%= simple_form_for(@movie) do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :poster_url %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<div style="display: flex; justify-content: space-between;">
  <h1><%= @movie.title %></h1>
  <div style="border: 1px solid black; background-color: lightgray; padding: 10px;">
    <%= link_to "Edit this movie", edit_movie_path(@movie) %>
  </div>
</div>

<div style="background-color: lightgray; border-radius: 5px; padding: 10px 30px;">
  <h2><%= @movie.overview %></h2>
  <h2>Rating: <%= @movie.rating %></h2>
</div>
<hr>
<%= link_to "Back to list", movies_path %>
<%= link_to "Delete this movie", movie_path(@movie.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>